### ISSUE TITLE
Support 6.0 doesn't build due to exception from Fody

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Host#104]
`Unknown custom metadata item kind: 7`

Pretty sure that is related to the breaking change MS did, we have to update Fody and move the tag

https://builds.particular.net/viewLog.html?buildId=188832&tab=buildResultsDiv&buildTypeId=NServiceBus_NServiceBusHost_1Build`

cc @simoncropp

**Comment by SimonCropp** [comment]
Yes this is correct

**Comment by ramonsmits** [comment]
@SimonCropp @andreasohlund Is this obsolete? As master is now on 7.0?
