### ISSUE TITLE
Compare assembly redirects between app.config and NServiceBus.Host.exe.config

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Host#108]
Detect if the `NServiceBus.Host.exe.config` file contains all assembly redirects that the `app.config`. contains. This should be possible as we should have read access to both configuration files.
## Who's affected
- All customers that "forget" to create/update the `NServiceBus.Host.exe.config` with assembly redirects.
## Symptoms
- Exceptions like: `Could not load file or assembly 'XXX, Version=x.x.x.x, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxx' or one of its dependencies.'

**Comment by danielmarbach** [comment]
I think this would really help a lot of users. See also #42 and related issues linked

**Comment by timbussmann** [comment]
Can we make sure this detection runs before any assembly loading fails?
