### ISSUE TITLE
Should we deprecate profiles?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Host#109]
There is currently a TODO

https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/Profiles/Handlers/LiteProfileHandler.cs#L10

I would suggest that we deprecate the profiles for vNext?

**Comment by danielmarbach** [comment]
Can you elaborate why?

**Comment by andreasohlund** [comment]
Why to deprecate?

Users can just put what ever code they want in their `IConfigureThisEndpoint`, pretty much like the the bootstrapper shows:

https://github.com/Particular/NServiceBus.Bootstrap.WindowsService/blob/develop/src/NServiceBus.Bootstrap.WindowsService/ProgramService.cs#L55


Ie the profiles don't really bring much value at the moment

**Comment by ramonsmits** [comment]
@andreasohlund I think profiles more or less one of the USP of the host. I've used profiles in the past to easily have different behavior like MSDTC usage and logging and persistence options for different environments (dev vs staging vs production). It's nice to control them from the commandline. Removing them would mean customers now need to write their own profile logic that can be driven from the command line.

**Comment by andreasohlund** [comment]
Profiles vs 

```
if(Environment.GetCommandLineArgs().Contains("DEV")
{
    config.Recoverability().Immediate(c=>c.Disable());
}

```

doesn't seem to be a huge selling point?

**Comment by SimonCropp** [comment]
+1 to killing profiles. with the code API they have a consistent environment switching when they use env variables, config files, db config etc
