### ISSUE TITLE
DefineEndpointName does not run EndpointConfiguration.ValidateEndpointName(...) like in the constructor 

### ISSUE THREAD

**Issue by serbrech** [Particular/NServiceBus.Host#110]
As a result, if you use the Host and define the endpointName with `@localhost` suffix, it fails miserably trying to append`@localhost` a second time.

Few solutions mostly based on tastes

1. Make the validation method public and reuse it in the extension method.
2. Duplicate the 2 validation lines in the extension method.
3. Extract a public SetEndpointName as a method on the EndpointConfiguration, use it in the constructor and remove the extension

Number 3 makes the API confusing by giving 2 ways of doing the same thing.
Number 1 duplicates the validation, but it's very trivial code.
Number 2 expose the validation method, but it's not harmful.

References

- ValidateEndpointName: https://github.com/Particular/NServiceBus/blob/6.0.0/src/NServiceBus.Core/EndpointConfiguration.cs#L214-L225
- DefineEndpointName: https://github.com/Particular/NServiceBus.Host/blob/7.0.0/src/NServiceBus.Hosting.Windows/EndpointConfigurationExtensions.cs#L15
- https://docs.particular.net/nservicebus/hosting/nservicebus-host/?#specify-endpoint-name-defined-in-code

**Comment by serbrech** [comment]
Meh, looks like github didn't handle the fixup & force push with the link to the issue. commit 5e00c86e38d13f87656a343a9417c30c68d8b30a includes tests. let me know if you want a PR or if you prefer a different implementation

**Comment by ramonsmits** [comment]
@serbrech Thanks for your report. It seems that `DefineEndpointName` is introduced in 7.0.0 as previously it was only possible to do this via an attribute if you didn't want to use the namespace as the endpoint name.

https://github.com/Particular/NServiceBus.Host/pull/92 contains a bit of info but it seems that validation was not considered.

@Particular/nservicebus-maintainers Is there a specific reason why validation was not performed?

**Comment by andreasohlund** [comment]
Seems like a misstake, :+1: to add validation to the host method as well

**Comment by serbrech** [comment]
Are you happy with my implementation? If yes i can turn it into a pull request if that's easier.

**Comment by timbussmann** [comment]
I agree with @andreasohlund, that check most likely just slipped in between. Sounds like a bug to me. Also 👍 to add the validation.

**Comment by ramonsmits** [comment]
@Particular/host-maintainers  @Particular/nservicebus-maintainers This is an improvement but would it warrant a patch release? It's not a bug in the sense that is fixes a runtime issue but more a refactoring. I would like to park this to the next minor so it can piggyback.

**Comment by andreasohlund** [comment]
:+1: for next minor since this doesn't seem to fit our patch definition (message loss etc)

**Comment by ramonsmits** [comment]
@serbrech Thanks for creating the issue and PR. It will be part of the next major or minor.
