### ISSUE TITLE
Should we blow up when scanning for the endpoint config?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Host#114]
I'm pretty sure we ignored scanned assemblies in the past but now we blow up at:

https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/EndpointTypeDeterminer.cs#L159

if for example the wrong version of RavenDB is used with no redirects in `NServiceBus.Host.exe.config`.

While writing this this seems more like a bug since we iterate over the "scannable assemblies"

https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/EndpointTypeDeterminer.cs#L157

Repro:

https://groups.google.com/d/msgid/particularsoftware/60f5b934-284e-41d8-a83d-cb3f78971c61%40googlegroups.com?utm_medium=email&utm_source=footer

cc @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
@andreasohlund the code looks exactly the same https://github.com/Particular/NServiceBus.Host/commit/e7b344c1b033397244f39ea5431b3aae8faee41b#diff-83065923a4ac73b9ac2dd6ec50736110R166 as before

**Comment by andreasohlund** [comment]
Found the issue together with @timbussmann and @danielmarbach . In v6 the scanner will return partially scannable assemblies as "scannable". The fix is to have the host use the .Types property of the results instead. I will raise a PR.

@Particular/azure-maintainers fyi this problem exists for the azure host as well. I will raise a PR there as well https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/develop/src/NServiceBus.Hosting.Azure.HostProcess/Program.cs#L81

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus.Host/issues/115
