### ISSUE TITLE
Injecting IMessageHandlerContext with Dependency Injection

### ISSUE THREAD

**Issue by iverds** [Particular/NServiceBus.Host#117]
In version 5 we had a component that took IBus as a dependency, and found a header based on the CurrentMessageContext property on IBus.

```
public class UsernameService : IUsernameService
{
        private readonly IBus _bus;

        public UsernameService(IBus bus)
        {
            _bus = bus;
        }

        public string GetUserName()
        {
            return _bus.CurrentMessageContext.Headers["user"];
        }
    }
}
```

In version 6, this is not longer possible (due to the deprecated IBus), and IMessageHandlerContext doesn't seem to be registered in the container.

Is there anyway I can register IMessageHandlerContext , or do I have to rewrite the code to take IMessageHandlerContext  as a parameter?

**Comment by janovesk** [comment]
Hi, iverds!

You are correct. We do not register the IMessageHandlerContext in the container. The primary reason being that we can't assume child containers can rebind in a consistent way in the new async/await world. We've made a conscious choice to make any state created per message explicitly available in context objects. This choice is why you now get an instance of  IMessageHandlerContext passed as an argument to all handler invocations.

More background on why we went down this route:
Discussion at https://groups.google.com/forum/#!topic/particularsoftware/mOzr6l0Lhzg
http://www.planetgeek.ch/2016/04/26/avoid-threadstatic-threadlocal-and-asynclocal-float-the-state-instead/
Daniel Marbach presentation at NDC Oslo https://vimeo.com/172111826

So _the recommendation is to embrace this and pass the context object_ you get from the handler down into whatever code you are calling, making the dependency explicit.

If you don't want to do this, you can still register the context in the container or a static AsyncLocal through a custom behavior yourself. 

### Container
```
class ContextBehavior : Behavior<IInvokeHandlerContext>
{
    public override Task Invoke(IInvokeHandlerContext context, Func<Task> next)
    {
        var contextAccessor = context.Builder.Build<ContextAccessor>();
        contextAccessor.Context = context;
        return next();
    }
}

public class ContextAccessor
{
    public IMessageHandlerContext Context { get; set; }
}

public class MyService
{
    private readonly ContextAccessor _contextAccessor;

    public MyService(ContextAccessor contextAccessor)
    {
        _contextAccessor = contextAccessor;
    }

    public void DoServiceStuff()
    {
        var context = _contextAccessor.Context;
    }
}
```
Also remember to register the `ContextAccessor` as scoped lifestyle in your container at startup.

### AsyncLocal
```
class ContextBehavior : Behavior<IInvokeHandlerContext>
{
    public override Task Invoke(IInvokeHandlerContext context, Func<Task> next)
    {
        ContextAccessor.Set(context);
        return next();
    }
}

public static class ContextAccessor //Requires .NET 4.6.1 for AsyncLocal. Use CallContext.GetLogicalData("context")/CallContext.SetLogicalData("context", value) if you are targeting something older
{
    static AsyncLocal<IMessageHandlerContext> _context = new AsyncLocal<IMessageHandlerContext>();
    public static IMessageHandlerContext Get() => _context.Value;
    public static void Set(IMessageHandlerContext context) => _context.Value = context;
}

public class MyService
{
    public void DoServiceStuff()
    {
        var context = ContextAccessor.Get();
    }
}
```

Hope that helps!

Jan Ove

**Comment by danielmarbach** [comment]
Hi @iverds 

We release a component called UniformSession that simplifies the migration. 

have a look over here https://discuss.particular.net/t/nservicebus-uniformsession-1-0-0-major-release-available/162

Daniel
