### ISSUE TITLE
Windows service recovery not kicking in when service fails connect after first recovery

### ISSUE THREAD

**Issue by Tsjunne** [Particular/NServiceBus.Host#119]
The situation is as follows:
* NServiceBus.Host is configured with service recovery to restart indefinitely after 1 minute delay
* CircuitBreakers are armed after transport outage (RabbitMQ)
* 2 minutes later services shuts down
* 1 minute later windows service recovery kicks in
* Transport is still unreachable and service fails to restart
* No more windows recovery actions kick in from this point

So even if the service is configured to recover multiple times, it will never attempt to recover more than once, if the transport is not available by the first try.
Is this a correct observation? 
If so, is there much use to configure service recovery if additional monitoring needs to be set up to attempt service restart in case of prolonged outage?

Is there any way to make the service start up, even if it can't connect to the transport, and let the circuitbreakers do the shutdown? This behavior would tie in beter with the service recovery options

**Comment by bording** [comment]
@Tsjunne Can you provide a bit more detail about what happens to the service process when "Transport is still unreachable and service fails to restart" occurs? Why does that lead to no more windows recovery actions?

**Comment by Tsjunne** [comment]
I tested this on my local machine running a local RabbitMQ. 

![image](https://cloud.githubusercontent.com/assets/2286860/23726867/2ec65978-0456-11e7-92ca-c35b2b4bbadd.png)

I shut down the broker at [22:54:17] while the service is running

`2017-03-08 22:54:02.764 INFO  DefaultFactory Logging to 'D:\Code\Projects\NSBCriticalError\NSBCriticalError\bin\Debug\' with level Info` 
`2017-03-08 22:54:03.168 INFO  NServiceBus.LicenseManager License expires on 21/06/2017 0:00:00` 
`2017-03-08 22:54:17.470 WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for 'NSBCriticalError.Retries MessagePump' is now in the armed state` 
`2017-03-08 22:54:17.470 WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for 'NSBCriticalError.TimeoutsDispatcher MessagePump' is now in the armed state` 
`2017-03-08 22:54:17.470 WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for 'NSBCriticalError.Timeouts MessagePump' is now in the armed state` 
`2017-03-08 22:54:17.470 WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for 'NSBCriticalError MessagePump' is now in the armed state`

I set the circuitbreaker timeout to 30 seconds, so the service crashes after the critical error is triggered:

`2017-03-08 22:54:47.479 WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for 'NSBCriticalError.Timeouts MessagePump' will now be triggered`
`2017-03-08 22:54:47.480 WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for 'NSBCriticalError MessagePump' will now be triggered`
`2017-03-08 22:54:47.479 WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for 'NSBCriticalError.TimeoutsDispatcher MessagePump' will now be triggered`
`2017-03-08 22:54:47.479 WARN  NServiceBus.Transport.RabbitMQ.MessagePumpConnectionFailedCircuitBreaker The circuit breaker for 'NSBCriticalError.Retries MessagePump' will now be triggered`
`2017-03-08 22:54:47.501 ERROR NServiceBus 'NSBCriticalError.Timeouts MessagePump' connection to the broker has failed ... (omitted stack trace)`

It registeres as a service failure for Windows, causing it to kick in the restart after 1 minute.
![eventlog](https://cloud.githubusercontent.com/assets/2286860/23726093/4ff66c80-0453-11e7-9502-7066b0b11cae.PNG)

One minute later Windows attempts to restart the service:

`2017-03-08 22:55:48.567 INFO  DefaultFactory Logging to 'D:\Code\Projects\NSBCriticalError\NSBCriticalError\bin\Debug\' with level Info` 
`2017-03-08 22:55:48.975 INFO  NServiceBus.LicenseManager License expires on 21/06/2017 0:00:00` 
`2017-03-08 22:55:51.253 ERROR NServiceBus.StartableEndpoint Receiver Main failed to start.
RabbitMQ.Client.Exceptions.BrokerUnreachableException ... (omitted stack trace)` 
`2017-03-08 22:55:51.272 ERROR NServiceBus.GenericHost Exception when starting endpoint.
RabbitMQ.Client.Exceptions.BrokerUnreachableException ... (omitted stack trace)`

The service fails to start, since the broker is still down, but this doesn't register with the Service Control Manager as a service failure. So the windows service recovery doesn't kick in anymore.

The full log file for the run
[nsb_log_2017-03-08_0.txt](https://github.com/Particular/NServiceBus.Host/files/829127/nsb_log_2017-03-08_0.txt)

**Comment by bording** [comment]
@Tsjunne Thanks for the extra info. So when the endpoint starts up the second time, the unhandled exceptions do cause the process to crash. I'm assuming that it does show up as an error in the Event Log, right?

If that's the case, then we'd need to try and find out why the Service Control Manager is ignoring that crash.

**Comment by Tsjunne** [comment]
The failing startup doesn't seem to register anything in the eventlog.
There are no more entries after the entry of the initial failure at [22:54:47]. So it looks like a failure in the startup sequence is not threated the same way as a crash after startup.

**Comment by gbiellem** [comment]
@bording  Windows Service Control Manager Recovery restarts are trigger by non zero exit codes.  Do we set an exitcode if the startup fails?

**Comment by bording** [comment]
@gbiellem I don't think we explicitly set an exit code anywhere, but I would have thought an unhandled exception would inherently result in a non-zero value.

**Comment by gbiellem** [comment]
I'd expect so too.   My first thought when I read the issues was "TopShelf bug".   It's a bit of a pain to test as the execution paths are slightly different when's run as a service vs as a console app.  A quick scan of the Topshelf fork we use led me to be a little suspicious but yet to do any definitive testing

**Comment by gbiellem** [comment]
I reproed this using  the NServiceBus.Host sample 
I modified it to throw an exception just after endpoint config,
When run from the command line it wrote the exception to the Windows eventlog and returned an errorcode but when run as a service the exception does not get logged to Windows eventlog and service restart doesn't happen. So something is off.

**Comment by ramonsmits** [comment]
As this is causing outage for our customers this is a critical bug. Based on our support policy this means we need to create the following releases:

- 7.0.1 (Core V6) #120
- 6.0.1 (Core V5)
- 5.0.12 (Core V5)

**Comment by ramonsmits** [comment]
@SeanFarmar FYI 7.0.1 is available, 6.0.1 is remaining.
