### ISSUE TITLE
Critical time and SLA metrics not enabled by default

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Host#124]
Documentation states that:

> In the NServiceBus Host this counter is enabled by default.

https://docs.particular.net/nservicebus/operations/performance-counters?version=perfcounters_1#critical-time-configuration

> In the NServiceBus Host the SLA violation countdown counter is enabled by default. But the value can be configured either by the above API or using a EndpointSLAAttribute on the instance of IConfigureThisEndpoint.

https://docs.particular.net/nservicebus/hosting/nservicebus-host/#performance-counters-sla-violation-countdown

Critical time should be enabled by default and SLA counter if the attribute value is set.

**Comment by seanfarmar** [comment]
> https://docs.particular.net/nservicebus/operations/performance-counters?version=perfcounters_1#critical-time-configuration

Fixed in the docs (there is a new link to the host documentation)

We still need to look at this:

> In the NServiceBus Host the SLA violation countdown counter is enabled by default. But the value can be configured either by the above API or using a EndpointSLAAttribute on the instance of IConfigureThisEndpoint.

> https://docs.particular.net/nservicebus/hosting/nservicebus-host/#performance-counters-sla-violation-countdown
