### ISSUE TITLE
Update host to accommodate new NServiceBus.Metrics.PerformanceCounters package

### ISSUE THREAD

**Issue by kbaley** [Particular/NServiceBus.Host#125]
Performance counters will be marked as obsolete in NSB.Core 6.2 and included in a separate `NServiceBus.Metrics.PerformanceCounters` package. One of the changes is that the `EnableSLAMonitoring` method no longer has an empty parameter overload so the `PerformanceCountersProfileHandler` will need to be modified to read the value of the `EndpointSLA` attribute and provide it to the method.

**Comment by andreasohlund** [comment]
EnndpointSLQ and all profiles have been obsoleted so I think we can close this

https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/EndpointSLAAttribute.cs
