### ISSUE TITLE
A failure as service stop results in error recovery to restart the service after the configured recovery delay

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Host#126]
In [7.0.1 exception handling was handled on both the OnStart and OnStop](https://github.com/Particular/NServiceBus.Host/blob/7.0.1/src/NServiceBus.Hosting.Windows/WindowsHost.cs#L29-L56) this to fix #119. Windows Service Recovery is now working in case the service process crashes. However, a failure during OnStop now not only stops the service process but will trigger Windows Service Recovery to 'restart' the process even though the Service Control Manager (SCM) triggered a STOP prior to the process exiting with a negative exit code.

This has the unintended effect that is an administrator stops the endpoint for maintenance that it by default will automatically restart after 60 seconds.

To fix this we need the OnStop to return a positive exit code so SCM will not initiate recovery. Unless a positive exit code will not work, then we will have to use zero (0).

**Comment by gbiellem** [comment]
@ramonsmits 👍 

Neat - Where did find that a positive exitcode does the trick?  I assumed you'd have to return 0 to prevent it firing the error recovery

**Comment by ramonsmits** [comment]
@gbiellem I didn't tested that yet but in my memory I always thought negative codes are system errors and positive codes are input/user errors. So if positive doesn't work as expected I'll use `0`.

**Comment by gbiellem** [comment]
@ramonsmits  Looks like this isn't a bug, just a configuration issue.  I didn't notice before but the "Stop" behavior can be controlled through the services UI

![capture](https://cloud.githubusercontent.com/assets/2351700/24584923/7a8c28b4-17c1-11e7-911e-c3a6c7bd4244.PNG)

**Comment by ramonsmits** [comment]
I asked the customer if the checkbox was set and that was confirmed meaning that explained the stop behavior.
