### ISSUE TITLE
Obsolete IWantToRunWhenEndpointStartsAndStops

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Host#135]
Given that we are adding a WARN to the host and deprecating things like profiles. Should we also consider deprecating `IWantToRunWhenEndpointStartsAndStops `since we can provide the feature as a self-contained snippet in the upgrade guide? Or is it too early and should we "just" add a WARN to that interface?

@Particular/host-maintainers @SimonCropp @andreasohlund thoughts? Also influences how we proceed with https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/102

**Comment by andreasohlund** [comment]
I've actually added this to the "migration" guide already 

https://github.com/Particular/docs.particular.net/pull/3173/files#diff-533ba6b5650e9d33e9f6f7573c66dd59R64

On the fence regarding if we obsolete with WARN or ERROR. Given that we want to give users some time to migrate away perhaps keep supporting is is ok since its not a big maintenance burden for us?

**Comment by danielmarbach** [comment]
I'm ok with that. So let's just add the same deprecation note as on `IConfigureThisEndpoint`?

**Comment by danielmarbach** [comment]
I updated the cloud host PR https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/102

**Comment by andreasohlund** [comment]
>I'm ok with that. So let's just add the same deprecation note as on IConfigureThisEndpoint?

👍

**Comment by seanfarmar** [comment]
>So let's just add the same deprecation note as on IConfigureThisEndpoint?
Does that mean we add a deprecation note on `IWantToRunWhenEndpointStartsAndStops`  in @andreasohlund's [PR](https://github.com/Particular/docs.particular.net/pull/3173/)?

**Comment by andreasohlund** [comment]
Thinking a bit more about this I wonder if a warning adds any value given
that IConfigureThisEndpoint is already obsoleted?

**Comment by danielmarbach** [comment]
Well the assembly could be referenced elsewhere and a type there could implement the runner. Then that assembly would also indicate the obsolete. Maybe I'm overthinking this but I definitely think it would not hurt adding it.

**Comment by andreasohlund** [comment]
>Well the assembly could be referenced elsewhere

Good point, I will add it

**Comment by andreasohlund** [comment]
PR is green https://github.com/Particular/NServiceBus.Host/issues/135 @danielmarbach can you review and merge so I can get the first beta out?

**Comment by danielmarbach** [comment]
Approved. LGTM. I will not merge it since I'm not part of this maintainer group
