### ISSUE TITLE
PR #132 removed `IConfigureLogging`

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Host#140]
PR #132 removed `IConfigureLogging` and `IConfigureLoggingForProfile<T>` which probably removed as `IConfigureLogging` was marked with:

```c#
[ObsoleteEx(
        TreatAsErrorFromVersion = "7.0",
        Message = "Configure logging in the constructor of the class that implements IConfigureThisEndpoint.",
        RemoveInVersion = "8.0")]
```

There is no reason to remove these interfaces. Logging configuration does not need to be done in the constructor.

@seanfarmar and I tested this on host 7.0.0 and 7.0.2 due to https://github.com/Particular/docs.particular.net/issues/3054 and worked correctly for all logging initialization scenarios:

- from the constructor
- using a `IConfigureLoggingForProfile<Lite>` implementation
- in `IConfigureThisEndpoint.Customize`

I think we need to revert that change as this is an essential part of the profile feature.

My assumption here is that I think the intent of the obsolete was probably to mark it for obsoletion in the source package, but not in the host package. As the code was linked, but not duplicated it got also marked obsolete in the host.

**Comment by ramonsmits** [comment]
@andreasohlund @SimonCropp Thoughts?

**Comment by SimonCropp** [comment]
IConfigureLoggingForProfile and IConfigureLogging  are both problematic since any host/core/user code that is executed prior to those interfaces being run will write log entries to the wrong location. logging config should be the very first line in any app startup

**Comment by ramonsmits** [comment]
@SimonCropp That is true, problem is only that `IConfigureLoggingForProfile<T>` wasn't marked as obsolete. If it should have been, we need to drop 7.0.3 and add that obsolete if we want to drop it in 8.0.0

**Comment by andreasohlund** [comment]
We never make any hard promises to "pre-obsolete" things so its fine to just obsolete with ERROR in v8?

**Comment by ramonsmits** [comment]
I just tested this, it works as expected when running the Lite profile:

    NServiceBus.Host.exe NServiceBus.Lite

No NServiceBus log files gets created.


```c#
using NServiceBus;
using NServiceBus.Logging;

[EndpointName("Samples.NServiceBus.Host")]
public class EndpointConfig : IConfigureThisEndpoint
{
    public void Customize(EndpointConfiguration endpointConfiguration)
    {
        LogManager.GetLogger("Config").InfoFormat("Bloop!");

        endpointConfiguration.EnableInstallers();
        endpointConfiguration.UsePersistence<LearningPersistence>();
        endpointConfiguration.UseTransport<LearningTransport>();
    }
}

class ProductionLoggingHandler : NServiceBus.Hosting.Profiles.IConfigureLoggingForProfile<Lite>
{
    public void Configure(IConfigureThisEndpoint specifier)
    {
        log4net.Config.XmlConfigurator.Configure();
        LogManager.Use<Log4NetFactory>();
    }
}
```

**Comment by ramonsmits** [comment]
@andreasohlund True but is it really needed? The above code shows I think the earliest log entry written by us otherwise the NServiceBus log file would have been created right?

**Comment by SimonCropp** [comment]
does logging in their EndpointConfig  it will go to the wrong file

**Comment by SimonCropp** [comment]
also anything that goes wrong with our code prior to the IConfigureLoggingForProfile goes to the wrong location

**Comment by ramonsmits** [comment]
Not needing to revert those changes.
