### ISSUE TITLE
AssemblyScanner couldn't enumerate all types

### ISSUE THREAD

**Issue by TraGicCode** [Particular/NServiceBus.Host#152]
I'm upgrading an endpoint from v5 to v6 and when i run our endpoint, which is using NServiceBus.Host as the host i'm getting a bunch of warnings and then an exception saying the assemblyscanner could not enumerate all types in our contracts assemblies and the NServiceBus.RavenDB Assembly.

Below is the log output from the host:

```


2018-12-31 06:59:32.944 WARN  NServiceBus.Hosting.Helpers.AssemblyScanner Could not enumerate all types for 'NServiceBus.RavenDB, Version=4.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
It looks like you may be missing binding redirects in the config file for the following assemblies:
Raven.Client.Lightweight, Version=3.5.0.0, Culture=neutral, PublicKeyToken=37f41c7f99471593
Raven.Abstractions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=37f41c7f99471593
For more information see http://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.100).aspx

2018-12-31 06:59:33.194 WARN  NServiceBus.Hosting.Helpers.AssemblyScanner Could not enumerate all types for 'ProductXXX.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Try to add the following binding redirects to the config file:
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
            <assemblyIdentity name="NServiceBus.Core" publicKeyToken="9fc386479f8a226c" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
        </dependentAssembly>
    </assemblyBinding>
</runtime>

2018-12-31 06:59:33.288 WARN  NServiceBus.Hosting.Helpers.AssemblyScanner Could not enumerate all types for 'ZZZ.MessageContracts, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null'.

Try to add the following binding redirects to the config file:
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
            <assemblyIdentity name="NServiceBus.Core" publicKeyToken="9fc386479f8a226c" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
        </dependentAssembly>
    </assemblyBinding>
</runtime>

```

The NServiceBus.Core binding redirect is already present in my Endpoints app.config so i'm not sure what i need to do at this point to resolve this problem.

**Comment by timbussmann** [comment]
Hey @TraGicCode 

When using the NServiceBus.Host package, assembly redirects need to be configured in the NServiceBus.Host.exe.config file, not the endpoint's app config (see this doco section fore more details: https://docs.particular.net/nservicebus/hosting/nservicebus-host/?version=host_7#application-domains). This is a bit unfortunate but one of the quirks with the host package.

You might want to double check your package dependencies and make sure that the package versions and their dependencies line up correctly so you won't need assembly redirects at all.  e.g. make sure to use the latest version of NServiceBus.RavenDB (4.2.6 right now) which supports RavenDB.Client 3.5.

Please let me know if those steps help.

**Comment by TraGicCode** [comment]
Closing, I simply removed the nservicebus.host package and used the dotnet core templates since thisnpackage is deprecated

**Comment by timbussmann** [comment]
Hey @TraGicCode 

Thanks for the update! The issues you ran into are part of the reason we'd like to deprecate the host. I think using the dotnet core template approach makes more sense if possible, so I'm glad to hear you were able to make it work 👍 I hope the switch wasn't too inconvenient.
