### ISSUE TITLE
Support delayed start argument

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Host#34]
Currently it is possible to set the dependsOn by adding arguments to the host. A user also asked whether we can add the delayed start as an argument. I looked quickly into it and it doesn't seem that our version of TopShelf really supports that. So should we support delayed start?

https://groups.google.com/forum/#!searchin/particularsoftware/$20NServiceBus$20Service$20hangs/particularsoftware/_KlA4Tc1w00/5AsGDSKypk0J

@johnsimons  thoughts?

**Comment by johnsimons** [comment]
Duplicate https://github.com/Particular/NServiceBus/issues/2597 ?

**Comment by SimonCropp** [comment]
dont think we should go to extra effort to add a feature that windows provides OOTB https://github.com/Particular/NServiceBus/issues/2597#issuecomment-66541351

**Comment by danielmarbach** [comment]
@SimonCropp I can relate to that. The contra argument would be we are already supporting some of those arguments like `dependsOn` in the host therefore it feels incomplete to not support delayedStart. Thoughts?

**Comment by johnsimons** [comment]
@danielmarbach how about putting this through requirements and see what others think ?

**Comment by cjoergensen** [comment]
'Delayed start' and 'Interactive' (The service will prompt the user at installation for the service credentials) flags would be very helpful for us.
