### ISSUE TITLE
Upgrade to NServiceBus v6

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Host#41]
Place holder to link PRs against for upgrade to NSB v6

**Comment by petersgiles** [comment]
FYI, I have a pending PULL https://github.com/Particular/NServiceBus.Host/pull/46 just needs to have final version of v6 put in it

**Comment by timbussmann** [comment]
@petersgiles I can't follow. That PR was merged a long time ago? Seems like we can close this one?

**Comment by petersgiles** [comment]
@timbussmann this issue seems to be a placeholder to remind @danielmarbach of something

But yeah I'll close it
