### ISSUE TITLE
Endpoint fails because of exceptions thrown when host scanning assemblies

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Host#42]
## Who's affected
- Anyone that uses NServiceBus host and assembly redirects needed for essential assemblies
## Symptoms
- Self-hosted code stops to work when hosted with NServiceBus host. 
## Additional information

NServiceBus host is using `EndpointTypeDeterminer` to scan assemblies in order to find endpoint configuration. When it's doing so, `AssemblyScanner` [can throw exception](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L145) on assembly loading. When that happens, assembly is not included in scanned assemblies result. The [list of scanned assemblies is passed later into endpoint`s appdomain for loading](https://github.com/Particular/NServiceBus.Host/blob/master/src/NServiceBus.Hosting.Windows/Program.cs#L61) and the list will not contain any assemblies that failed loading during host startup. This can cause Endpoint to fail if excluded assembly was essential for endpoint.

Example: an assembly required a binding redirect that is added to endpoint`s app.config. When NSB host is scanning this assembly, it will not have the binding redirect in`nservicebus.host.exe.config`and assembly will fail loading, therefore not passed into endpoint`s appdomain for loading. This will result in exception and failure to execute endpoint. 

When failing, very difficult to trace why this is happening since exception is not logged anywhere in the host. 

**Related GH issue with details**: https://github.com/Particular/NServiceBus.AzureBlobStorageDataBus/issues/6
## Additional affected repos

https://github.com/Particular/NServiceBus.Host.AzureCloudService
## Potential fix

Do not pass a list of scanned assemblies to the endpoint if exception were thrown. Similar to what's already done when [running NSB host via command line](https://github.com/Particular/NServiceBus.Host/blob/master/src/NServiceBus.Hosting.Windows/Program.cs#L121)

**Comment by SeanFeldman** [comment]
@andreasohlund if we fix this one, we'll need to fix Azure host process as well.

**Comment by ramonsmits** [comment]
Assemblies could still fail to load for unknown reasons. If we modify this behavior there is the possibility that we can not start due to assembly load exceptions while that would not be any issue during runtime.

We should just log load issues as warnings and not swallow them. They are not errors if they would not result in runtime issues. For example TypeMock stuff...

**Comment by SeanFeldman** [comment]
@ramonsmits change would not prevent endpoint from loading, it will prevent filtering of assemblies for the endpoint.

**Comment by SeanFeldman** [comment]
@danielmarbach with work taking place for v6, I think we should get this in as well. Y/N?

**Comment by SeanFeldman** [comment]
@Particular/nservicebus another customer ran into this. Should we fix it?

**Comment by danielmarbach** [comment]
@SeanFeldman would it be possible for you to verify this with v7. We can then prioritize this for the next minor release if it is still an issue

**Comment by robbihun** [comment]
Adding this as related as i just spent several hours on it using v7.0.0 of nservicebus.host.exe

[https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/113](https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/113)

**Comment by SeanFeldman** [comment]
Thank you @robbihun.
This would also then need to be done for Azure host.

**Comment by ramonsmits** [comment]
@SeanFeldman I think #115 is the same. If you agree then you can close #42
