### ISSUE TITLE
Fix LiteProfileHandler

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Host#44]
Fix [`LiteProfileHandler`](https://github.com/Particular/NServiceBus.Host/compare/UpgradeHostV6?expand=1#diff-67d15a42e88874f016b2e44bb70f2fc9R15) by hooking into the pipeline and potentially replace the standard `MoveFaultsToErrorQueue` behavior with a discarding one

copied from here https://github.com/Particular/NServiceBus.Host/pull/40

**Comment by andreasohlund** [comment]
The lite profile doesn't seem to provide value anymore, I'd say we obsolete it

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - is this still targeted for the 7.0.0 milestone?

**Comment by andreasohlund** [comment]
We didn't get to it, milestone removed
