### ISSUE TITLE
Deprecate WcfIntegration in the Host

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Host#45]
Deprecate or move out WcfIntegration depending on outcome of https://github.com/Particular/FeatureDevelopment/issues/362

copied from here https://github.com/Particular/NServiceBus.Host/pull/40

**Comment by timbussmann** [comment]
as stated in https://github.com/Particular/V6Launch/issues/122, it seems like the WcfIntegration has been removed, but obsoletes are still missing?

**Comment by timbussmann** [comment]
Obsoletes were added in #103, docs update is here: https://github.com/Particular/docs.particular.net/pull/1886

closing this.
