### ISSUE TITLE
What happens in case of an unhandled exception?

### ISSUE THREAD

**Issue by cqs-dsafronov** [Particular/NServiceBus.Host#55]
https://groups.google.com/forum/#!topic/particularsoftware/cd9ulZ7SNo4

Product: NServiceBus.Host 6.0.0.0

The host failed unexpectedly while being idle, there are no errors in the log. There is user code that logs  ```AppDomain.CurrentDomain.UnhandledException``` .

Last two messages on the text log:

2016-02-09 23:10:28.6412 DEBUG Polling for timeouts at 09/02/2016 23:10:28. 
2016-02-09 23:10:29.1566 DEBUG Polling next retrieval is at 09/02/2016 23:11:29. 

Event log:

Faulting application name: NServiceBus.Host.exe, version: 6.0.0.0, time stamp: 0x54734af4
Faulting module name: clr.dll, version: 4.6.81.0, time stamp: 0x5584e818
Exception code: 0xc00000fd
Fault offset: 0x0000000000068ad7
Faulting process id: 0x1be8
Faulting application start time: 0x01d160039f52621d
Faulting application path: E:\Applications\TradeIdeaManager\IdeaProcessor\NServiceBus.Host.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 658a3307-cf82-11e5-80db-005056bba086
Faulting package full name: 
Faulting package-relative application ID: 

Is this because of TopShelf design or it's unrelated?

https://github.com/Topshelf/Topshelf/issues/150
https://github.com/Topshelf/Topshelf/issues/212

Thanks.

**Comment by andreasohlund** [comment]
Really sorry for the delay, we really dropped the ball on this one!

Is the problem still happening?

Can you send over you configuration?

Are you changing the logging configuration in anyway?

Is there any crash dumps available that we can look at?

**Comment by cqs-dsafronov** [comment]
All NServiceBus host windows services were set to always restart on failure automatically. So there is no way to know if the issue reoccurs unless someone will be checking event log everyday.

It would be interesting to know your opinion about https://github.com/Topshelf/Topshelf/issues/150 and  Topshelf/Topshelf#212 and whether they could be affecting user-defined unhandled exception interception.

Thank you.

**Comment by andreasohlund** [comment]
>All our NServiceBus host windows services were set to always restart on failure automatically.

:+1: that's the way to go

>It would be interesting to know your opinion about Topshelf/Topshelf#150 and Topshelf/Topshelf#212 and whether they could be affecting user-defined unhandled exception interception.

That sounds plausible, that said we're on a quite old version of topshelf so I would have to do some more digging to be sure. We're moving away from the NServiceBus.Host in favor of http://docs.particular.net/nservicebus/hosting/windows-service#bootstrapping-nuget

That way you get full control over your service, would this be interesting for you? Just reach out if you need some help. (email, gitter, etc)

I'll close this one for now.

Again, really sorry for the delay!

**Comment by cqs-dsafronov** [comment]
@andreasohlund
Thank you, I understand. We might look into the new hosting approach in future.
Also no problem about delay, I would contact support directly if it was more urgent.
