### ISSUE TITLE
Implement IWantToRunWhenEndpointStarts

### ISSUE THREAD

**Issue by kbaley** [Particular/NServiceBus.Host#60]
Connects to https://github.com/Particular/NServiceBus/issues/3342

With `IWantToRunWhenBusStartsAndStops` becoming obsolete, each host will need to implement this functionality (including tests).

**Comment by andreasohlund** [comment]
@kbaley how about we close this one as a duplicate of Particular/NServiceBus#3342 since that one is tracking this? (cc @colin-higgins )
