### ISSUE TITLE
Async all the way to the top

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Host#61]
Currently `GenericHost` synchronously executes the async calls of NSB with `GetAwaiter().GetResult()` inside `Start` and `Stop` which are void methods. We should favour a design where we are async all the way to the top level of the call stack and only synchronise on the top level.

**Comment by boblangley** [comment]
@Particular/tf-v6-launch-plat-dev Should this be part of the v6 launch? Especially since we [are moving a core interface to the host](https://github.com/Particular/NServiceBus/issues/3342).

**Comment by andreasohlund** [comment]
@danielmarbach since this have no effects on the end users is this a must have for v6?

**Comment by danielmarbach** [comment]
@andreasohlund took me 10 minutes to fix it and uncovered a bug

https://github.com/Particular/NServiceBus.Host/pull/80

**Comment by andreasohlund** [comment]
PR merged, this is done
