### ISSUE TITLE
IWantToRunWhenEndpointStartsAndStops Instance Scanning Discrimination

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus.Host#66]
Depends on https://github.com/Particular/NServiceBus.Host/pull/64

Connects To: https://github.com/Particular/NServiceBus/issues/3342

`IWantToRunWhenEndpointStartsAndStops` is being ported from Core to Host

There is currently no discrimination in the assembly scanning for instances registered through the `EndpointConfiguration`. This is existing behavior in core v5.

This means that there will be duplicates picked up after assembly scanning runs unless the user excludes those explicit types from assembly scanning.

Proposed fix:

```
            var startableStoppableInstances =
                context.Settings.GetOrDefault<List<IWantToRunWhenEndpointStartsAndStops>>()
                ?? new List<IWantToRunWhenEndpointStartsAndStops>();

            var typesToExclude = new HashSet<Type>(startableStoppableInstances.Select(i => i.GetType()));

            context.Settings.GetAvailableTypes()
                .Where(IsConcrete)
                .Where(IsIWantToRunWhenEndpointStartsAndStops)
                .Where(t => !typesToExclude.Contains(t))
                .ToList()
                .ForEach(t => context.Container.ConfigureComponent(t, DependencyLifecycle.InstancePerCall));
```

**Comment by colin-higgins** [comment]
ping @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment]
> There is currently no discrimination in the assembly scanning for instances registered through the EndpointConfiguration

Was this different when the code was inside nsb.core?

**Comment by colin-higgins** [comment]
@timbussmann No this is an existing defect for core

**Comment by andreasohlund** [comment]
PR is merged, closing this one
