### ISSUE TITLE
Updating to pre-release Version 7, overwrites endpointConfiguration.cs

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus.Host#81]
When upgrading NServiceBus.Host to the pre-release beta version on Nuget, the user created EndpointConfiguration.cs gets prompted to get overwritten and users can potentially lose their custom endpoint configuration.

Is there any need for this to be overwritten?

**V6 Beta Customer Feedback:** Relates to https://github.com/Particular/V6Launch/issues/35

---

Update:
Version 7 of the host will prompt the user for an overwrite. The user can choose not to overwrite. In previous versions of the host, the file was always overwritten.

**Comment by SimonCropp** [comment]
@indualagarsamy https://github.com/Particular/NServiceBus.Host/pull/76

**Comment by indualagarsamy** [comment]
@bording - is that change part of beta 2 that's out on nuget?

**Comment by bording** [comment]
Yes, the behavior talked about in #76 is the prompting for overwriting. Previously when you upgraded, the file was overwritten without a prompt.

The nuget package includes a default `EndpointConfiguration.cs` so that when you install it for the first time you have the required configuration. 

When upgrading, it now detects that you already have one, so it prompts you about overwriting it with the default or not.

**Comment by SimonCropp** [comment]
@bording 

> Previously when you upgraded, the file was overwritten without a prompt.

That was not the behavior in v6 https://github.com/Particular/NServiceBus.Host/blob/master/packaging/nuget/nservicebus.host/install.ps1#L107

The file being overwritten was a bug in v7. so from a user perspective "Previously when you upgraded, the file was overwritten without a prompt" is not correct.

**Comment by bording** [comment]
> The file being overwritten was a bug in v7. so from a user perspective "Previously when you upgraded, the file was overwritten without a prompt" is not correct.

I went back and tested some previous versions, and despite that code being there in v6, it wasn't actually working correctly. I tested an upgrade from a previous version to v6, and the file was silently overwritten.

**Comment by indualagarsamy** [comment]
@bording - If a user already has a EndpointConfiguration.cs file, then we should leave that file alone. No need to prompt to override. We should just leave it alone.

**Comment by SimonCropp** [comment]
@bording yeah just confirmed overwriting endpoint is a bug in updating from 5 to 6. so u r correct

**Comment by bording** [comment]
> @bording yeah just confirmed overwriting endpoint is a bug in updating from 5 to 6. so u r correct

That's why I opted to move to a built-in nuget feature (content section in the nuspec file) vs. trying to fix a buggy/fragile powershell script.

**Comment by tmasternak** [comment]
Do we want to fix bug in V5 in addition to changes for V6?

**Comment by bording** [comment]
> Do we want to fix bug in V5 in addition to changes for V6?

It would be easy to backport the nuspec changes if this is something we want to do.

**Comment by indualagarsamy** [comment]
@bording - please confirm. As it stands, there's no changes for V7 of the host right? i.e. There will be a prompt that will inform the user about the override. 
For v6 of the host are we back porting this?

**Comment by SimonCropp** [comment]
@indualagarsamy AFAIK currently no plans to port it back

**Comment by bording** [comment]
> @bording - please confirm. As it stands, there's no changes for V7 of the host right? i.e. There will be a prompt that will inform the user about the override. 

@indualagarsamy Correct, nothing has changed there.

**Comment by indualagarsamy** [comment]
If this needs to be back ported, please raise an another issue. I've updated the issue with this comment. 
>Version 7 of the host will prompt the user for an overwrite. The user can choose not to overwrite. In previous versions of the host, the file was always overwritten.
