### ISSUE TITLE
Updating to pre release Version 7, the error on IConfigureThisEndpoint isn't very clear

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus.Host#82]
When updating the endpoints from Version 6 of the host to Version 7 of NServiceBus.Host, the compilation error on IConfigureThisEndpoint isn't very friendly.
This might cause issues for users during upgrade.

Relates to https://github.com/Particular/V6Launch/issues/36

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - are we going to do anything about this?

**Comment by andreasohlund** [comment]
Yea, lets fix it, what's the current obsolete message that is displayed?

**Comment by andreasohlund** [comment]
Do we even have a obsolete message? can't find any?

https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/obsoletes.cs#L30

**Comment by danielmarbach** [comment]
V7 is out. I'm closing this. Feel free to raise another issue with action points for the next minor or major version.
