### ISSUE TITLE
Updating to pre-release Version 7 causes issues with log4net dependencies

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus.Host#83]
Relates to https://github.com/Particular/V6Launch/issues/36

**Customer Feedback:**
I verified our handlers were working, updated to 5.2.14 and re-validated. From there I went through the process of re-updating to NSB6 and encountered the log4net issue again.
 
At this point I started up a brand new solution (console application) with the following code
```c#
var ec = new EndpointConfiguration("KWT");
            ec
                .UsePersistence<InMemoryPersistence>();
            IStartableEndpoint e = null;
            Task.Run(async () => e = await Endpoint.Create(ec)).Wait();
            LogManager.Use<Log4NetFactory>();
            e.Start();
            Console.ReadLine();
``` 
Starts up without issue and does not exception.
 
When I switch this project to ‘Class Library’ and add NServiceBus.Host 7.0.0=beta0002 (Prerelease) I get the binding mismatch error for log4net 1.2.11.
 
Reverting this change makes it work again.

**Comment by SimonCropp** [comment]
did u put the binding redirect in `NServiceBus.Host.exe.config` as well?

**Comment by kevin-whalley-gc** [comment]
I'm confused about what you're asking - there is no NServiceBus.Host.exe.config in the build output, or included in either the beta package or the 6.0 package.

**Comment by indualagarsamy** [comment]
@kevin-whalley-gc - Although, adding NServiceBus.Host.exe.config is a pain, sometimes that's the only way especially when it comes to asm redirects when using NServiceBus.Host. See a similar issue here: https://github.com/Particular/NServiceBus.RabbitMQ/issues/10#issuecomment-28670804. 

Can you try creating a new config filed called, `NServiceBus.Host.exe.config` and then add the asm redirect and see if that helps?

**Comment by indualagarsamy** [comment]
@kevin-whalley-gc - I did more digging.

So I got to the root cause of the problem. It's unfortunately how Log4Net is being versioned.
See: https://www.nuget.org/packages/log4net/

Log4net packages are versioned, {insert your favorite expletive} weird.
2.0.5 is the latest nuget package. The assembly version for package 2.0.5 is assembly version 1.2.15
2.0.4 package uses assembly version 1.2.14
2.0.3 package uses assembly version 1.2.13
2.0.2 package uses assembly version 1.2.12
2.0.1 package *also uses* assembly version 1.2.12
2.0.0 package uses assembly version 1.2.11

In Version 5 of NServiceBus endpoints, you are referencing our nuget package, NServiceBus.Log4Net version 1.0.0. which uses Log4Net nuget package 2.0.0, which means assembly version 1.2.11.
https://github.com/Particular/NServiceBus.Log4Net/blob/master/src/NServiceBus.Log4Net/packages.config#L4 
And therefore in Version 5, there's no conflict because you are using 1.2.11 as well.

The release branch for NServiceBus.Log4Net for NServiceBus Core Version 6, uses the latest Log4Net package, i.e. 2.0.5, which is assembly version 1.2.15
https://github.com/Particular/NServiceBus.Log4Net/blob/release-2.0.0/src/NServiceBus.Log4Net/packages.config#L4
Now there is a conflict in the asm version and the only way to resolve it in the case of NServiceBus.Host is to add a NServiceBus.Host.exe.config. 

**What's the way to move forward?**
- Add NServiceBus.Host.Exe.Config with the asm directs. This is going to be a pain because for customers who have more than 1 NServiceBus.Host endpoint to try and do the "special" deployment step of getting this setup.
- Switch to NLog: Unfortunately, the log4net dependency issues is because of how Log4Net chooses to do their versioning. They increment their assembly version with every version release! This will break every time there's a log4net nuget upgrade, resulting in you having to add asm redirects. A better logging library would be NLog. NLog is better maintained, versioned acc to .Net versioning best practices. See: https://www.nuget.org/packages/NLog/
The assembly version is maintained as [MajorVersion].0.0.0 as it should be. This is the same practice we follow in NServiceBus Nuget / Asm file versioning as well. 
- Switch to a self hosting model: Same model as console app, with easy switch to Windows Service. See: http://docs.particular.net/nservicebus/hosting/windows-service. The common parts of starting the bus, etc can be abstracted away to a common library to keep the code clean to all of the endpoints.  No weirdness of including a .exe as a reference in your project either.

For the NServiceBus.Host, unfortunately, we cannot make any special provisions in the powershell install.ps1 script concerning log4net, because the .host.exe.config will be required for any other assemblies that require asm changes. 

@Particular/nservicebus-maintainers  - please comment on why asm redirects needs to be added to NServiceBus.Host.Exe.Config. @andreasohlund thought it could be due to the asm scanning that the host does and then passes the list of asms found to the appdomain that runs the endpoint.

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - Can you verify if the need for having the asm redirects in the NServiceBus.Host.Exe.Config is because of asm scanning that the host does? If so, that sounds like a legitimate bug in the host to me which needs fixing as @kevin-whalley-gc pointed out.

**Comment by kevin-whalley-gc** [comment]
@indualagarsamy, we are able to use log4net 2.0.5 (1.2.15) with NServiceBus Log4Net 1.0 and NServiceBus.Host 6.0...

If I follow the issue requiring assembly redirects in vNext for NServiceBus Log4Net and Host would I not need them currently? (I don't)

**Comment by bording** [comment]
The issue here is that while the NServiceBus.Log4Net package lists its minimum dependency on log4net as >= 2.0.0, its actually built against 2.0.5. When you install the beta package, it won't install 2.0.5, and instead tries to add binding redirects that aren't actually useful.

If you manually update to log4net  2.0.5 and remove any leftover binding redirects, it should work correctly. I was able to test it myself that and following those steps fixed the problem.

**Comment by indualagarsamy** [comment]
@bording - I did more research on this. Also I discussed with @SimonCropp.
I agree with @SimonCropp that we can't change nuspec because of the following reason:

- NServiceBus.Log4net is compiled with 1.2.15.0. The nuspec minimum range we specify for NServiceBus.Log4net follows semver which starts at 2.0.0. In the case of Log4Net, this defaults to 1.2.11.0 assembly version.  So, when you install NServiceBus.Log4net version 2.0.0, it pulls in Log4net 1.2.11.0 (asm). Even if we adjust our nuspec to 2.0.4, which will use 1.2.15.0, the minute log4net releases a new version, you'd need a asm redirect. It doesn't make sense to change our nuspec policy for this because it adds no value. While at the quick onset, it might seem like it avoids the exception, it no longer holds good, if log4net nuget package is updated.

- I tested this. I created a host project with the following packages:

```xml
<package id="log4net" version="2.0.0" targetFramework="net452" />
  <package id="NServiceBus" version="6.0.0-beta0001" targetFramework="net452" />
  <package id="NServiceBus.Host" version="7.0.0-beta0002" targetFramework="net452" />
  <package id="NServiceBus.Log4Net" version="2.0.0-beta0001" targetFramework="net452" />
```

and it threw this exception:

```
An exception of type 'System.IO.FileLoadException' occurred in NServiceBus.Core.dll but was not handled in user code

Additional information: Could not load file or assembly 'log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

After I updated the Log4net nuget package, it worked without any exceptions. Because the latest version of log4net is at the moment 1.2.15.0

The thing is tomorrow, if Log4net releases another new version, you'd need to add the asm redirect.

Rather than a multi-step nuget dependency update, you could do:
Install-Package NServiceBus.Host [ProjectName] -DependencyVersion HighestMinor

For more details, see: http://docs.nuget.org/Consume/Package-Manager-Console-PowerShell-Reference#update-package

I am going to close this issue, however what @kevin-whalley-gc raised, i.e. why does the asm redirect need to be in the NServiceBus.Host.Exe.Config is still legit for which I will raise a different issue.

**Comment by indualagarsamy** [comment]
@kevin-whalley-gc - I've raised a new issue for having to add the asm redirects in the host.exe.config.

**Comment by indualagarsamy** [comment]
@kevin-whalley-gc - Update. After further discussions:
The NServiceBus.Log4net Beta version is now compiled with 2.0.0 version of Log4net. i.e. 1.2.11.0
So, if you're using a higher version of log4net, you'll now need to a asm redirect in the NServiceBus.Host.exe.config. I've raised a separate issue on why we need to do that for the @Particular/nservicebus-maintainers to chime in.
