### ISSUE TITLE
Why do asm redirects have to be defined in NServiceBus.Host.Exe.Config?

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus.Host#84]
Currently all assembly redirects needs to be done in NServiceBus.Host.Exe.Config.
This adds to extra deployment steps and a lot of NServiceBus.Host users aren't aware of this and leads to a lot of time in troubleshooting this. 

Why? 

Relates to https://github.com/Particular/V6Launch/issues/36
https://github.com/Particular/NServiceBus.Host/issues/83

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - Please fix this as it causes a lot of confusion or document this appropriately.

**Comment by danielmarbach** [comment]
Assembly redirects happen either on App level or on machine level, see https://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.110).aspx

So if someone is using the NServiceBus.Host.exe this process becomes the App. Therefore, all redirects have to be put in place on that level. We had several discussions in the past whether the black magic of the host actually provides more benefits and grieve. In this case, I'd say this is another example where it causes more grieve. 

@Particular/nservicebus-maintainers another proof that we should move towards deprecating the host rather sooner than later? // cc @SimonCropp

**Comment by andreasohlund** [comment]
I was pretty sure that https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/HostProgram.cs#L122 was meant to solve that. Since if we run into a scanning issue we won't pass the list of scanned asms to the appdomain and essentially let it "rescan" ?

I'll digg deeper

**Comment by andreasohlund** [comment]
Found it, there is a bug in the core https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs where we blow up even of the scanner is asked to not throw when there are missing assembly redirects.

After talking to @SimonCropp we concluded that the best way to fix this is to copy paste the scanner to the host since its only the host that needs the "don't throw on bad assemblies" flag. That way we can make the scanner internal in the core

cc @Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
I might have jumped the gun, I don't seem to be able to repro the issue. I can get 

```

<packages>
  <package id="log4net" version="2.0.0" targetFramework="net46" />
  <package id="NServiceBus" version="6.0.0-beta0002" targetFramework="net46" />
  <package id="NServiceBus.Host" version="7.0.0-beta0002" targetFramework="net46" />
  <package id="NServiceBus.Log4Net" version="2.0.0-beta0001" targetFramework="net46" />
</packages>

```

to work by adding a app.config (no NServiceBus.Exe.Config needed) with: 

```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.15.0" newVersion="1.2.11.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

```

Config code:

```

public class EndpointConfig:IConfigureThisEndpoint
    {
        public void Customize(EndpointConfiguration configuration)
        {
            LogManager.Use<Log4NetFactory>();
            configuration
                .UsePersistence<InMemoryPersistence>();

            configuration.SendFailedMessagesTo("error");

            Console.Out.WriteLine("Started");
        }
    }

```

@indualagarsamy what am I doing wrong?

**Comment by andreasohlund** [comment]
@indualagarsamy what did we decide when we talked about this? (I can't see to repro it)

**Comment by indualagarsamy** [comment]
@andreasohlund let me try a scenario and I'll post my results up here in this issue.

**Comment by indualagarsamy** [comment]
Closing this issue. I can't repro it either. I'll reopen if I can repro this consistently.

**Comment by indualagarsamy** [comment]
I was able to repro this based on a customer support case. 

1. Use the nservicebus.hosting sample 
https://docs.particular.net/samples/hosting/nservicebus-host/
2. Add nuget package `NServiceBus.NHibernate` to the project
3. Note that it adds the correct assembly redirects to the app.config
4. Run the sample and it throws an exception.
5. Add the same assembly redirects to the NServiceBus.Host.Exe.Config and set the copy always so that the debug dir has this file and run the sample and it works.

**Comment by ramonsmits** [comment]
@indualagarsamy is this failing the host init? Do you have exception info?

**Comment by seanfarmar** [comment]
Should we close this? @indualagarsamy @ramonsmits
