### ISSUE TITLE
EndpointConfig added on every update if moved to different folder

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.Host#97]
I moved my endpoint config to a Config folder in the endpoint project. Every time I now upgrade my NServiceBus.Host package, the EndpointConfig.cs gets added. 

Not a lot of effort to manually remove of course, and quite quickly obvious if the same name space is used, but just wanted to make sure this is 'known' ;)

**Comment by danielmarbach** [comment]
@janpieterz thanks for bringing it up. Unfortunately, there is not much we can do here. We use the endpoint config in the root as a required convention. We think it would be fairly risky to change the convention to do a deep search in the project structure. Closing this
